package CardInfo

import (
	"io/ioutil"
	"net/http"
	"os"
)

const metaFilePath string = ".asset/card/metadata/card.json"

func CheckMetaFileExist() bool {
	if _, err := os.Stat(metaFilePath); os.IsNotExist(err) {
		return false
	}
	return true
}

func GetAllCards() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	req, err := http.NewRequest("GET", "https://omgvamp-hearthstone-v1.p.mashape.com/cards", nil)
	if err != nil {
		panic(err)
	}
	req.Header.Set("X-Mashape-Key", "4I9OQ5fbixmshBp579mJU44NK203p16ibiSjsn2jHyJ1mVZAou")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err)
	}
	result, err := ioutil.ReadAll(resp.Body)

	if err != nil {
		panic(err)
	}

	file, err := os.Create(metaFilePath)

	if err != nil {
		panic(err)
	}

	defer file.Close()

	file.Write(result)
	defer resp.Body.Close()
}
